#
# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
grpc:
  client:
    channels:
      - name: "default"
        tls:
          enabled: "false"
      - name: "payment"
        host: "payment-http"
        port: 80
        tls:
          enabled: "false"
      - name: "shipping"
        host: "shipping-http"
        port: 80
        tls:
          enabled: "false"
coherence:
  topic:
    enabled: false
  proxy:
    enabled: false
  tracing:
    ratio: -1
otel:
  sdk:
    disabled: true
  service:
    name: Orders
  traces:
    exporter: otlp
  exporter:
    otlp:
      traces:
        endpoint: http://jaeger-inmemory-instance-collector:4317
