{
 "title": "Sockshop Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "label_values(application_com_oracle_coherence_examples_sockshop_helidon_orders_OrderResource_newOrder_seconds, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Instructions",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Sockshop Dashboard for namespace: $Namespace\n\n\n\nPlease select the namespace above to view details for for that namespace.\n\n\n"
  },
  {
   "title": "Total Orders",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_examples_sockshop_helidon_orders_OrderResource_newOrder_seconds_count{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Orders Received per Minute",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_examples_sockshop_helidon_orders_OrderResource_newOrder_rate_per_second{namespace=~\"$Namespace\"} * 60)"
    }
   ]
  },
  {
   "title": "Avg Order Processing Time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(application_com_oracle_coherence_examples_sockshop_helidon_orders_OrderResource_newOrder_mean_seconds{namespace=~\"$Namespace\"} > 0)  "
    }
   ]
  },
  {
   "title": "Successful Payments",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_examples_sockshop_helidon_payment_DefaultPaymentService_payment_success_total{namespace=~\"$Namespace\"})  "
    }
   ]
  },
  {
   "title": "Failed Payments",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_examples_sockshop_helidon_payment_DefaultPaymentService_payment_failure_total{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Payment Success Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_examples_sockshop_helidon_payment_DefaultPaymentService_payment_success_total{namespace=~\"$Namespace\"}) / (sum(application_com_oracle_coherence_examples_sockshop_helidon_payment_DefaultPaymentService_payment_success_total{namespace=~\"$Namespace\"}) + sum(application_com_oracle_coherence_examples_sockshop_helidon_payment_DefaultPaymentService_payment_failure_total{namespace=~\"$Namespace\"}))"
    }
   ]
  },
  {
   "title": "Orders Processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Orders" }
   ],
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_examples_sockshop_helidon_orders_OrderResource_newOrder_seconds_count{namespace=~\"$Namespace\"}) - (sum(application_com_oracle_coherence_examples_sockshop_helidon_orders_OrderResource_newOrder_seconds_count{namespace=~\"$Namespace\"} offset $__interval))",
     "legendFormat": "Orders"
    }
   ]
  },
  {
   "title": "Payments Processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(application_com_oracle_coherence_examples_sockshop_helidon_payment_DefaultPaymentService_payment_success_total{namespace=~\"$Namespace\"}) - (sum(application_com_oracle_coherence_examples_sockshop_helidon_payment_DefaultPaymentService_payment_success_total{namespace=~\"$Namespace\"} offset $__interval))",
     "legendFormat": "Payment Successes"
    },
    {
     "expr": "sum(application_com_oracle_coherence_examples_sockshop_helidon_payment_DefaultPaymentService_payment_failure_total{namespace=~\"$Namespace\"}) - (sum(application_com_oracle_coherence_examples_sockshop_helidon_payment_DefaultPaymentService_payment_failure_total{namespace=~\"$Namespace\"} offset $__interval))",
     "legendFormat": "Payment Failures"
    }
   ]
  },
  {
   "title": "Overall Order Processing Time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "min(application_com_oracle_coherence_examples_sockshop_helidon_orders_OrderResource_newOrder_min_seconds{namespace=~\"$Namespace\"} > 0)",
     "legendFormat": "Minimum"
    },
    {
     "expr": "avg(application_com_oracle_coherence_examples_sockshop_helidon_orders_OrderResource_newOrder_mean_seconds{namespace=~\"$Namespace\"} > 0)",
     "legendFormat": "Mean"
    },
    {
     "expr": "max(application_com_oracle_coherence_examples_sockshop_helidon_orders_OrderResource_newOrder_max_seconds{namespace=~\"$Namespace\"})",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "gRPC Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_grpc_requests_meter_total{namespace=~\"$Namespace\"}) - (sum(vendor_grpc_requests_meter_total{namespace=~\"$Namespace\"} offset $__interval)) > 0",
     "legendFormat": "Role: {{role}}"
    }
   ]
  }
 ]
}