#
# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: carts
spec:
  cluster: SockShop
  role: Carts
  replicas: 1
  image: ghcr.io/oracle/coherence-helidon-sockshop-carts:latest
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  application:
    type: helidon
  jvm:
    memory:
      heapSize: 2g
    args:
      - "-Dhelidon.serialFilter.ignoreFiles=true"
      - "-Dhelidon.serialFilter.pattern=*"
      - "-Dhelidon.serialFilter.failure.action=WARN"
  coherence:
    metrics:
      enabled: true
  ports:
    - name: http
      port: 7001
      service:
        name: carts
        port: 80
      serviceMonitor:
        enabled: true
    - name: metrics
      serviceMonitor:
        enabled: true
